appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: pRIMbuZxccuSe8b+Lf9OPgVB3BbEdUqSxT6PVp+RHd07z9gi00OQ8w3Agh2xC5058AT85uQDQmFWm6DfqQSwjS9qtdygUQ3V6Kz5QAOhL8K5Sl92fCTEbpHFkgtqNsIq5yMZ8IEBLr9P0q1IKAf4d500QzYt1QsWQfbevkV/5Q3z8TnAvcvWIUZO9wv9Mvuvs7Xjam7oW19ObXbgK4k2/KsZsmYew9gPcnFUCM/kybhRVI4lFGy/zBaUn+XcyuwvRT46H3OmCECojGuv6l8XNY+EXBJDL7yiFyA0R3DLujQFRn1GuM3t2c+NKWhTArtkDaOrEvfn3NQ/5LzD9aIQPpJe3a1x8K6jY2niyvtIpPP8RmV4zZNVIC1gxjkATg/3CmCtLTIevHzUGcy40jpAYoVuLssBHHXi7fA6PyQDRDZagzRJXieLIXT+o5jMzTtxlv3qsGJsP1akVpOD/6fUkq5Rjgk1z99IKJuEhFNFdQ61TsdmN0lqFrwUn9+dmGIfckniwsuTtwPa4mvfhgurkOxP/OdxWG+o6uG9Y1FRJtO/TvbHWHt/qLAKap9RvdSe8yANAdEKmiZtw2NEn9lreeT4ap9LpambLy7pinnootI4c/PkIT0JV5jUNgwENDU9Mfipgm8zEnTaGNxhTqw9QtqRIl+CbXgPMuE/r8VevJE=
conda_forge_output_validation: true
